<a href="https://colab.research.google.com/github/shixinzhu/DL-GoogleColab-2020/blob/master/Tensorflow_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"]="2"

import tensorflow as tf
print(tf.__version__)

2.3.1


In [3]:
!pip install tensorflow-gpu

In [5]:
physical_devices = tf.config.list_physical_devices("GPU")

In [8]:
x1 = tf.constant(4)
print(x1)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
x2 = tf.constant(4, shape=(1, 1))
print(x2)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [10]:
x3 = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x3)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [12]:
x4 = tf.constant(1, 2, 3)
print(x4)

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float64)


In [13]:
x5 = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x5)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [14]:
x6 = tf.ones((3, 3))
print(x6)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [15]:
x7 = tf.zeros((3, 3))
print(x7)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [16]:
x8 = tf.eye(3)
print(x8)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [17]:
x9 = tf.random.normal((3, 3), mean=0, stddev=1)
print(x9)

tf.Tensor(
[[ 0.59796685 -0.6319406   0.48407108]
 [ 0.5514735  -1.8403983  -0.43020806]
 [-2.1463203  -1.3888949  -0.43286723]], shape=(3, 3), dtype=float32)


In [18]:
x10 = tf.random.uniform((3, 3), minval=0, maxval=1)
print(x10)

tf.Tensor(
[[1.3864613e-01 3.8570714e-01 6.0349357e-01]
 [4.2163622e-01 2.0749366e-01 6.5891504e-01]
 [4.0376186e-04 6.2324405e-01 6.0876560e-01]], shape=(3, 3), dtype=float32)


In [19]:
x11 = tf.range(10)
print(x11)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [20]:
## cast
y = tf.cast(x11, dtype=tf.float32)
print(y)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [22]:
## elementwise

x21 = tf.constant([1, 2, 3])
y21 = tf.constant([4, 5, 6])

z21 = tf.add(x21, y21)
print(z21)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [25]:
## elementwise

x22 = tf.constant([1, 2, 3])
y22 = tf.constant([4, 5, 6])

z22 = tf.subtract(x, y)
print(z22)

z202 = x22 - y22
print(z202)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [27]:
## elementwise

x23 = tf.constant([1, 2, 3])
y23 = tf.constant([4, 5, 6])

z23 = tf.divide(x23, y23)
print(z23)

z203 = x23 / y23
print(z203)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [29]:
## elementwise

x24 = tf.constant([1, 2, 3])
y24 = tf.constant([4, 5, 6])

z24 = tf.multiply(x24, y24)
print(z24)

z204 = x24 * y24
print(z204)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [30]:
## elementwise

x25 = tf.constant([1, 2, 3])
y25 = tf.constant([4, 5, 6])

z25 = tf.tensordot(x25, y25, axes=1)
print(z25)

tf.Tensor(32, shape=(), dtype=int32)


In [31]:
## elementwise

x26 = tf.constant([1, 2, 3])
y26 = tf.constant([4, 5, 6])

z26 = x26 ** 3
print(z26)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)
