In [1]:
import numpy as np 

In [5]:
# 如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。
# 这要求维数相同，且各维度的长度相同。

a = np.array([1, 2, 3, 4]) 
b = np.array([10, 20, 30, 40]) 
c = a * b 

print (c)

[ 10  40  90 160]


In [6]:
# 当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。

a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])

print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
# 广播的规则:

# 让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。
# 输出数组的形状是输入数组形状的各个维度上的最大值。
# 如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
# 当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。