#### Numpy基础03 切片和索引

In [5]:
import numpy as np

In [ ]:
a = np.arange(10)
s = slice(2, 7, 2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])

In [ ]:
a = np.arange(10)  
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

In [ ]:
### 冒号 : 的解释：
### 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。
### 如果为 [2:]，表示从该索引开始以后的所有项都将被提取。
### 如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项

In [ ]:
a = np.arange(10)
print(a[2:])

In [ ]:
a = np.arange(10) 
print(a[2:5])

In [ ]:
a = np.linspace(1, 9, 9, dtype=int).reshape([3, 3])
print(a)
print('=============')
print(a[1:])

In [ ]:
a = np.linspace(1, 9, 9, dtype=int).reshape([3, 3])
print("第2列元素:")
print (a[...,1])   # 第2列元素
print()

print("第2行元素:")
print (a[1,...])   # 第2行元素
print()

print("第2列及剩下的所有元素:")
print (a[...,1:])  # 第2列及剩下的所有元素

In [6]:
a = np.linspace(1, 9, 9, dtype=int).reshape([3, 3])

In [7]:
y = a[[0,1,2],  [0,1,0]]  # 取 [(0, 0), (1, 5), (2, 0)]
print(y)

[1 5 7]


In [10]:
a = np.linspace(0, 11, 12, dtype=int).reshape([4, 3])
print ('我们的数组是：' )
print (x)
print ('\n')
rows = np.array([[0,0],[3,3]]) 
cols = np.array([[0,2],[0,2]]) 
y = a[rows,cols]  
print  ('这个数组的四个角元素是：')
print (y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


In [11]:
### 布尔索引
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]
