#### Numpy 基础06 统计函数

In [ ]:
import numpy as np 

# numpy.amin() 用于计算数组中的元素沿指定轴的最小值。
# numpy.amax() 用于计算数组中的元素沿指定轴的最大值。

a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
print ('我们的数组是：')
print (a)
print ('\n')
print ('调用 amin() 函数：')
print (np.amin(a,  1))          # 1: 按行
print ('\n')

print ('再次调用 amin() 函数：')
print (np.amin(a,0))        # 0: 按列
print ('\n')

print ('调用 amax() 函数：')
print (np.amax(a))         # 如果没有的话，则是整个数组中最大的值
print ('\n')

print ('再次调用 amax() 函数：')
print (np.amax(a, axis =  0))

In [ ]:
# numpy.ptp()函数计算数组中元素最大值与最小值的差（最大值 - 最小值）

In [ ]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
print ('我们的数组是：')
print (a)
print ('\n')

print ('调用 ptp() 函数：')
print (np.ptp(a))
print ('\n')

print ('沿轴 1 调用 ptp() 函数：')
print (np.ptp(a, axis =  1))
print ('\n')

print ('沿轴 0 调用 ptp() 函数：')
print (np.ptp(a, axis =  0))

In [6]:
# numpy.percentile() 百分位数是统计中使用的度量，表示小于这个值的观察值的百分比。 
# 函数numpy.percentile()接受以下参数。
# numpy.percentile(a, q, axis)

# 参数说明：

# a 输入数组
# q: 要计算的百分位数，在 0 ~ 100 之间
#  axis: 沿着它计算百分位数的轴

In [9]:
a = np.array([[10, 7, 4], [3, 2, 1]])
print ('我们的数组是：')
print (a)
 
print ('调用 percentile() 函数：')
# 50% 的分位数，就是 a 里排序之后的中位数
print (np.percentile(a, 50)) 

print()

# axis 为 0，在纵列上求
print (np.percentile(a, 50, axis=0)) 

print()
 
# axis 为 1，在横行上求
print (np.percentile(a, 50, axis=1)) 
print()
 
# 保持维度不变
print (np.percentile(a, 50, axis=1, keepdims=True))

我们的数组是：
[[10  7  4]
 [ 3  2  1]]
调用 percentile() 函数：
3.5

[6.5 4.5 2.5]

[7. 2.]

[[7.]
 [2.]]


In [10]:
# numpy.median() 函数用于计算数组 a 中元素的中位数（中值）

In [11]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])  
print ('我们的数组是：')
print (a)
print ('\n')
print ('调用 median() 函数：')
print (np.median(a))
print ('\n')
print ('沿轴 0 调用 median() 函数：')
print (np.median(a, axis =  0))
print ('\n')
print ('沿轴 1 调用 median() 函数：')
print (np.median(a, axis =  1))

我们的数组是：
[[30 65 70]
 [80 95 10]
 [50 90 60]]


调用 median() 函数：
65.0


沿轴 0 调用 median() 函数：
[50. 90. 60.]


沿轴 1 调用 median() 函数：
[65. 80. 60.]


In [ ]:
# numpy.mean() 函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。
# 算术平均值是沿轴的元素的总和除以元素的数量。

In [12]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print ('我们的数组是：')
print (a)
print ('\n')

print ('调用 mean() 函数：')
print (np.mean(a))
print ('\n')

print ('沿轴 0 调用 mean() 函数：')
print (np.mean(a, axis =  0))
print ('\n')

print ('沿轴 1 调用 mean() 函数：')
print (np.mean(a, axis =  1))

我们的数组是：
[[1 2 3]
 [3 4 5]
 [4 5 6]]


调用 mean() 函数：
3.6666666666666665


沿轴 0 调用 mean() 函数：
[2.66666667 3.66666667 4.66666667]


沿轴 1 调用 mean() 函数：
[2. 4. 5.]


In [13]:
# numpy.average() 
# numpy.average() 函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。