#### Numpy 基础02 数组相关知识

In [1]:
import numpy as np

In [2]:
# 生成 0 到 5 的数组， 设置返回类型位 float:
x =np.arange(5, dtype=float)
print (x)

[0. 1. 2. 3. 4.]


In [4]:
# 设置了起始值、终止值及步长：
x = np.arange(10,41,2)  
print (x)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [5]:
# 设置起始点为 1 ，终止点为 10，数列个数为 10。
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
# 设置元素全部是1的等差数列：
a = np.linspace(2,11,10)
print(a)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [18]:
# 将 endpoint 设为 false，不包含终止值
a = np.linspace(10, 20,  5, endpoint =  False)  
print(a)

[10. 12. 14. 16. 18.]


In [13]:
a = np.linspace(10, 20, 4, endpoint=True)
print(a)

[10.         13.33333333 16.66666667 20.        ]


In [19]:
# retstep 如果为 True 时，生成的数组中会显示间距，反之不显示。
a =np.linspace(1,10,10,retstep= False)
b =np.linspace(1,10,10,retstep= True)
print(a)
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


In [23]:
b =np.linspace(1,10,10).reshape([10,1])
print(np.linspace(1, 10, 10))
print(b)

print(np.linspace(1, 10, 10).reshape([5, 2]))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]


In [24]:
# 默认底数是 10
a = np.logspace(1.0,  2.0, num =  10)  
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [25]:
# 对数的底数设置为 2 
a = np.logspace(0,9,10,base=2)
print (a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
