#### Numpy 基础知识01 基本概念

In [1]:
# NumPy 最重要的一个特点是其 N 维数组对象 ndarray，它是一系列同类型数据的集合，以 0 下标为开始进行集合中元素的索引。
# - ndarray 对象是用于存放同类型元素的多维数组。
# - ndarray 中的每个元素在内存中都有相同存储大小的区域。

In [2]:
import numpy as np

In [3]:
print(np.eye(5))
print(np.eye(5).shape)
print(np.eye(5).size)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
25


In [4]:
a = np.arange(30)
print(a)
print(a.ndim)        #秩，即轴的数量或维度的数量
print(a.shape)       #数组的维度，对于矩阵，n 行 m 列
print(a.size)          #数组元素的总个数，相当于 .shape 中 n*m 的值
print(a.dtype)      # ndarray 对象的元素类型
print(a.itemsize) #ndarray 对象中每个元素的大小，以字节为单位
print(a.flags)       #ndarray 对象的内存信息
print(a.real)        #ndarray元素的实部
print(a.imag)       #ndarray元素的虚部
print(a.data)       #包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
1
(30,)
30
int64
8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [8]:
### Test 001 >>> >>>

a = np.array([[1,2,3],[4,5,6]]) 
print('Before shape :: ')
print(a) 

print()
print('After shape :: ')
a.shape = (1,6) 
print(a)

Before shape :: 
[[1 2 3]
 [4 5 6]]

After shape :: 
[[1 2 3 4 5 6]]


In [9]:
### Test 002 >>> >>>

a = np.arange(24) 
a.ndim  

b = a.reshape(2,4,3) 
print(b) 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [10]:
# numpy.itemsize
# This array attribute returns the length of each element of array in bytes.

x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

x = np.array([1,2,3,4,5], dtype = np.float32) 
print(x.itemsize)

1
4


In [11]:
# numpy.flags
# The ndarray object has the following attributes. Its current values are returned by this function.

x = np.array([1,2,3,4,5], dtype = np.float32) 
# print(x.flags)
print(x)

x = np.array([1,2,3,4,5]) 
# print(x.flags)
print(x)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [13]:
# 数组的创建
x = np.empty([3,2], dtype = int) 
print (x)
print(x.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [14]:
np.zeros((5,), dtype = np.int, order = 'F')

array([0, 0, 0, 0, 0])

In [15]:
# 默认为浮点数
x = np.zeros(5) 
print(x)

[0. 0. 0. 0. 0.]


In [16]:
# 设置类型为整数
y = np.zeros((5,), dtype = np.int) 
print(y)

[0 0 0 0 0]


In [17]:
#将列表转换为 ndarray

x =  [1,2,3] 
a = np.asarray(x)  
print (a)

[1 2 3]


In [ ]:
#将元组转换为 ndarray
x =  (1,2,3) 
a = np.asarray(x)  
print (a)

In [18]:
#将元组列表转换为 ndarray
x =  [(1,2,3),(4,5)] 
a = np.asarray(x)  
print (a)

[(1, 2, 3) (4, 5)]


In [19]:
#将列表转换为 ndarray 并设置了 dtype
x =  [1,2,3] 
a = np.asarray(x, dtype =  float)  
print (a)

[1. 2. 3.]


In [21]:
# numpy.frombuffer 用于实现动态数组
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)
print(a.size)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']
11


In [22]:
# numpy.fromiter 方法从可迭代对象中建立 ndarray 对象
# 使用 range 函数创建列表对象  
list=range(5)
it=iter(list)
 
# 使用迭代器创建 ndarray 
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]
